language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - composer run-script lint
  - composer run-script test-with-coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
